import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FoxNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div className="sm:px-12 px-5 py-4">
          <div className="relative flex flex-row items-center justify-between h-16">
            <div className="flex flex-row items-center">
              <Image src="/logo-img.svg" alt="Logo" width="39" height="32" />
              <h1 className="font-mono font-bold text-3xl p-2 hidden sm:block">
                FoxNews
              </h1>
            </div>
            <h1 className="font-mono font-bold text-sm hidden sm:block">
              Call Us (348)981.872 / hello@foxnews.com
            </h1>
            <h1 className="font-mono font-bold text-sm hover:underline hover:cursor-pointer hover:font-bold">
              Login
            </h1>
          </div>
        </div>
      </nav>
    </div>
  );
};

export default Home;
